#!/usr/bin/env python3
#
# Copyright 2017 Zegami Ltd

"""Turn KANJIDIC into a Zegami collection."""

import sys

from zegami_kanjidic.__main__ import main


if __name__ == "__main__":
    sys.exit(main(sys.argv))
